### ISSUE TITLE
非子View 区域也会触发滑动，且无法响应点击事件

### ISSUE THREAD

**Issue by 1022-zhang** [JarvisGG/NestedTouchScrollingLayout#4]

**Comment by JarvisGG** [comment]
空白区域的点击事件吗？

**Comment by 1022-zhang** [comment]
> 空白区域的点击事件吗？

点击及滑动触发区域事件 在 NestedTouchScrollingLayout 区域内，在子View 区域外；

**Comment by JarvisGG** [comment]
已经解决啦。请 api 1.2.1 尝试，感谢🙏

**Comment by 1022-zhang** [comment]
> 已经解决啦。请 api 1.2.1 尝试，感谢

感谢，已经解决掉了。辛苦
